### PR TITLE
Added Yen's auto thresholding algorithm

### PR DESCRIPTION
**Pull request by arijitkar98**
Yen's auto thresholding algorithm as discussed in this paper [Yen J.C., Chang F.J., and Chang S. (1995) “A New Criterion for Automatic Multilevel Thresholding”](http://ieeexplore.ieee.org/document/366472/)

### CODE REVIEW

**Comment by arijitkar98** [comment]
Ping @zygmuntszpak @Evizero

**Comment by zygmuntszpak** [comment]
@arijitkar98 Thank you for yet another contribution. I've downloaded the paper so I can familiarise myself with the details.

**Comment by zygmuntszpak** [comment]
The paper proposes a method for selecting multiple thresholds, whereas the implementation is for a single threshold. Perhaps it is better to write `Computes threshold for grayscale image using Yen's maximum correlation criterion for bilevel thresholding` instead of `Computes threshold for grayscale image using Yen's method.` in the docstring. 

I'd also suggest the following small changes.
```
prob_mass_function = counts./sum(counts)
prob_mass_function_sq = prob_mass_function.^2
cum_pmf = cumsum(prob_mass_function)
cum_pmf_sq_1 = cumsum(prob_mass_function_sq)
cum_pmf_sq_2 = reverse!(cumsum(reverse!(prob_mass_function_sq)))

# Equation (4) in the cited paper. 
criterion = log.(((cum_pmf[1:end-1].*(1.0 - cum_pmf[1:end-1])).^2) ./ (cum_pmf_sq_1[1:end-1].*cum_pmf_sq_2[2:end]))
```
My observations are based on the fact that there is no need to compute `prob_mass_function.^2` twice. Also, using `reverse!` instead of `reverse` means you won't be reallocating additional arrays unnecessarily. 

Other than that, thanks for such a clean and concise implementation!

On a different note, I wonder whether it would be worth starting a `Thresholds.jl` package since there are numerous other thresholding methods out there which might feel at home in their own package?

**Comment by arijitkar98** [comment]
@zygmuntszpak Thank you so much for the inputs. I have made the required changes.

**Comment by zygmuntszpak** [comment]
Looks good to me. Will have to wait for Evizero to merge if he agrees.

**Comment by arijitkar98** [comment]
Ping @Evizero

**Comment by Evizero** [comment]
Thank you @arijitkar98 for another contribution! And also a big thank you to @zygmuntszpak for your review expertise and time

**Pull request merged**
