### PR TITLE
Run ImageMagick & QuartzImageIO tests on travis

### PR DESCRIPTION
**Pull request by timholy**
Since changes to Images have the possibility of breaking the IO packages (see https://github.com/JuliaIO/ImageMagick.jl/pull/34), we should run those packages' tests when testing Images.

### CODE REVIEW

**Comment by timholy** [comment]
Looks like this has inadvertently revealed ways in which QuartzImageIO lags behind ImageMagick. Perhaps more importantly, I'm surprised that the QuartzImageIO method is getting called by `ImageMagick.save`.

**Comment by rsrock** [comment]
Looks like the test run on OS X that errored out with giant log is because the ImageMagick tests are being run using QuartzImageIO.  See these lines (around line 450, iirc)

```
INFO: Testing ImageMagick
IO
  > Binary png
WARNING: MethodError(QuartzImageIO.save,(FileIO.File{FileIO.DataFormat{:PNG}}
```

I do like the idea behind this, though.  I think it's a great idea to couple the tests.

**Comment by timholy** [comment]
Right, but what has me puzzled is that the test [looks like this](https://github.com/JuliaIO/ImageMagick.jl/blob/360c947635655d4f375f2b5e74eecb90421e0662/test/constructed_images.jl#L14).

...and hovering doubtfully over the comment button can occasionally be useful, giving one a chance to think a little more. The answer: looks like we need to tag a new version of ImageMagick, that may solve the problem.

**Comment by rsrock** [comment]
That is a curveball right there.  Hopefully the tagging fixes it!

**Comment by rdeits** [comment]
Is this still something we want? I can fix the conflicts and get this going again.

**Comment by timholy** [comment]
I'd say yes. Best to know if we do anything here that breaks the ability to load images. :+1:

**Comment by johnnychen94** [comment]
I assume this and #667 are outdated now?

**Pull request closed without merging**
