### PR TITLE
Using Statistics.var

### PR DESCRIPTION
**Pull request by tknopp**
Its used later in this file and I get a deprecation warning in my code.

### CODE REVIEW

**Comment by RalphAS** [comment]
We are extending `var` and `std` below, so they are qualified in all uses AFAICT. An additional `using` shouldn't hurt, but if you're using a (fairly recent) commit from master it shouldn't help either.

**Comment by tknopp** [comment]
no its not qualified in this line:
https://github.com/JuliaImages/Images.jl/blob/master/src/algorithms.jl#L80

**Comment by RalphAS** [comment]
My mistake.  You are of course correct.  Maybe when the test requirements are all tagged we can do a coverage analysis to avoid this kind of embarrassment.

**Comment by tknopp** [comment]
you can see here that its not covered: https://codecov.io/gh/JuliaImages/Images.jl/src/master/src/algorithms.jl#L72.
But don't worry 90% code coverage is pretty good.

**Pull request merged**
