### PR TITLE
convert tests from factcheck to testsets

### PR DESCRIPTION
**Pull request by jw3126**

### CODE REVIEW

**Comment by timholy** [comment]
This is a pretty massive conflict with #542 and the [images-next branch](https://github.com/timholy/Images.jl/tree/images-next).

**Comment by timholy** [comment]
Is this the product of a script? If so, I'd certainly be happy to have it run on `images-next`. One slightly unusual thing there: I added a string-tag to many FactCheck tests, simply because they give poor backtraces (one of the many advantages of testsets).

**Comment by Evizero** [comment]
are the `-->` more compareable to `==` or `===`? If the latter is the case than the tests might not be equivalent

**Comment by jw3126** [comment]
`-->` is `==` and `--> exactly(...)` is `===`. This is mostly work of a [script](https://github.com/jw3126/FactCheck2TestSets.jl), but also about 1 hour of manual fixup. So I could wait for images-next and do it again, but I can't do it several times. Just ping me when you want the final migration.

**Comment by timholy** [comment]
Fixed by #577 and #584. Thanks for your efforts, @jw3126, I'm sorry I didn't take advantage of your very kind offer!

**Pull request closed without merging**
