### PR TITLE
Bump Project.toml version and fix a test

### PR DESCRIPTION
**Pull request by ViralBShah**
@johnnychen94 @timholy There's a couple of tests failing here, which would be nice to resolve and then merge.

### CODE REVIEW

**Comment by johnnychen94** [comment]
The broken tests might be due to some internal incompatibility to Colors 0.13 and ColorTypes 0.12 -- most packages in JuliaImages don't directly depend on them (but instead via ImageCore).
Yet our ImageCore 0.10.4 release missed that.

We will need to find out what breaks the packages, fix that, and _also_ add the missing tests to ImageCore to prevent further breakage.

I'm not available this month, but I will do it in December if nobody does that before me.

**Comment by ViralBShah** [comment]
The issue is (and there may be more):

```
Histogram Equalisation: Error During Test at /Users/runner/work/Images.jl/Images.jl/test/exposure.jl:78
  Got exception outside of a @test
  ArgumentError: N0f8 is an 8-bit type representing 256 values from 0.0 to 1.0; cannot represent 2
  Stacktrace:
    [1] throw_converterror(::Type{N0f8}, x::Int64)
      @ FixedPointNumbers ~/.julia/packages/FixedPointNumbers/Dn4hv/src/FixedPointNumbers.jl:326
```

**Comment by ViralBShah** [comment]
@johnnychen94 Wonder if you might have a bit of time to take a look to get the tests to pass and tag a new release. I've bumped a lot of the dependent packages, and hoping this is not a major issue to fix.

**Comment by ViralBShah** [comment]
The failing test is simply this:

```
julia> imgeq = adjust_histogram(collect(0:1:255), Equalization(256,64,128))
ERROR: ArgumentError: N0f8 is an 8-bit type representing 256 values from 0.0 to 1.0; cannot represent 2
Stacktrace:
  [1] throw_converterror(::Type{N0f8}, x::Int64)
    @ FixedPointNumbers ~/.julia/packages/FixedPointNumbers/Dn4hv/src/FixedPointNumbers.jl:326
  [2] _convert
    @ ~/.julia/packages/FixedPointNumbers/Dn4hv/src/normed.jl:61 [inlined]
  [3] FixedPoint
    @ ~/.julia/packages/FixedPointNumbers/Dn4hv/src/FixedPointNumbers.jl:58 [inlined]
  [4] convert
    @ ./number.jl:7 [inlined]
  [5] gray
    @ ~/.julia/packages/ColorTypes/0RO5O/src/traits.jl:37 [inlined]
  [6] transform
    @ ~/.julia/packages/ImageContrastAdjustment/J15Ip/src/algorithms/common.jl:6 [inlined]
  [7] map!(f::ImageContrastAdjustment.var"#transform#4"{…}, dest::Vector{…}, A::Vector{…})
    @ Base ./abstractarray.jl:3364
  [8] transform_density!(out::Vector{…}, img::Vector{…}, edges::StepRangeLen{…}, newvals::Vector{…})
    @ ImageContrastAdjustment ~/.julia/packages/ImageContrastAdjustment/J15Ip/src/algorithms/common.jl:17
  [9] (::Equalization{Int64, Int64})(out::Vector{Int64}, img::Vector{Int64})
    @ ImageContrastAdjustment ~/.julia/packages/ImageContrastAdjustment/J15Ip/src/algorithms/equalization.jl:114
 [10] adjust_histogram!
    @ ~/.julia/packages/ImageContrastAdjustment/J15Ip/src/HistogramAdjustmentAPI/histogram_adjustment.jl:44 [inlined]
 [11] #adjust_histogram#3
    @ ~/.julia/packages/ImageContrastAdjustment/J15Ip/src/HistogramAdjustmentAPI/histogram_adjustment.jl:64 [inlined]
 [12] adjust_histogram
    @ ~/.julia/packages/ImageContrastAdjustment/J15Ip/src/HistogramAdjustmentAPI/histogram_adjustment.jl:59 [inlined]
 [13] adjust_histogram(::Vector{Int64}, ::Equalization{Int64, Int64})
    @ ImageContrastAdjustment.HistogramAdjustmentAPI ~/.julia/packages/ImageContrastAdjustment/J15Ip/src/HistogramAdjustmentAPI/histogram_adjustment.jl:74
 [14] top-level scope
    @ REPL[19]:1
Some type information was truncated. Use `show(err)` to see complete types.

```

**Comment by ViralBShah** [comment]
I'm disabling a couple of tests. I believe they actually pass erroneous inputs - and that there doesn't seem to be a fundamental issue in the dependent packages. I have marked these disabled tests as FIXME so that they can be found easily.

**Comment by ViralBShah** [comment]
It would be nice if @johnnychen94 and @timholy could take a look at the master. When this is registered, it should pull new versions of various packages in the Images ecosystem.

**Pull request merged**
