### PR TITLE
Updated: Run ImageMagick & QuartzImageIO tests on travis

### PR DESCRIPTION
**Pull request by rdeits**
Cleaned-up version of #468

### CODE REVIEW

**Comment by timholy** [comment]
The OSX QuartzImageIO tests failed, everything else looks great.

**Comment by rdeits** [comment]
I'll try to reproduce that locally and see what's going on.

**Comment by rdeits** [comment]
There seems to be a real issue with QuartzImageIO: https://github.com/JuliaIO/QuartzImageIO.jl/issues/43

**Comment by johnnychen94** [comment]
As we have switched the whole CI stack to Github Actions, this PR becomes outdated now. If there's still a need to test ImageMagick and QuartzImageIO (and even ImageIO) in Images.jl repo, we can open a new PR.

**Pull request closed without merging**
