### PR TITLE
Fix doc-string of imedge

### PR DESCRIPTION
**Pull request by mauro3**

### CODE REVIEW

**Comment by timholy** [comment]
Hmm, that docstring does need fixing. But shouldn't the fix be opposite this one?
```julia
julia> A = [linspace(0, 1, 10); zeros(3)] .* ones(5)'
13×5 Array{Float64,2}:
 0.0       0.0       0.0       0.0       0.0     
 0.111111  0.111111  0.111111  0.111111  0.111111
 0.222222  0.222222  0.222222  0.222222  0.222222
 0.333333  0.333333  0.333333  0.333333  0.333333
 0.444444  0.444444  0.444444  0.444444  0.444444
 0.555556  0.555556  0.555556  0.555556  0.555556
 0.666667  0.666667  0.666667  0.666667  0.666667
 0.777778  0.777778  0.777778  0.777778  0.777778
 0.888889  0.888889  0.888889  0.888889  0.888889
 1.0       1.0       1.0       1.0       1.0     
 0.0       0.0       0.0       0.0       0.0     
 0.0       0.0       0.0       0.0       0.0     
 0.0       0.0       0.0       0.0       0.0     

julia> g1, g2, mag, orient = imedge(A)
([0.0555556 0.0555556 … 0.0555556 0.0555556; 0.111111 0.111111 … 0.111111 0.111111; … ; 0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0], [0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0; … ; 0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0], [0.0555556 0.0555556 … 0.0555556 0.0555556; 0.111111 0.111111 … 0.111111 0.111111; … ; 0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0], [1.5708 1.5708 … 1.5708 1.5708; 1.5708 1.5708 … 1.5708 1.5708; … ; 0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0])                                  
                                                                                                                                                                                                                                             
julia> g1
13×5 Array{Float64,2}:                                                                                                                                                                                                                       
  0.0555556   0.0555556   0.0555556   0.0555556   0.0555556                                                                                                                                                                                  
  0.111111    0.111111    0.111111    0.111111    0.111111                                                                                                                                                                                   
  0.111111    0.111111    0.111111    0.111111    0.111111                                                                                                                                                                                   
  0.111111    0.111111    0.111111    0.111111    0.111111                                                                                                                                                                                   
  0.111111    0.111111    0.111111    0.111111    0.111111                                                                                                                                                                                   
  0.111111    0.111111    0.111111    0.111111    0.111111                                                                                                                                                                                   
  0.111111    0.111111    0.111111    0.111111    0.111111                                                                                                                                                                                   
  0.111111    0.111111    0.111111    0.111111    0.111111                                                                                                                                                                                   
  0.111111    0.111111    0.111111    0.111111    0.111111                                                                                                                                                                                   
 -0.444444   -0.444444   -0.444444   -0.444444   -0.444444                                                                                                                                                                                   
 -0.5        -0.5        -0.5        -0.5        -0.5                                                                                                                                                                                        
  0.0         0.0         0.0         0.0         0.0                                                                                                                                                                                        
  0.0         0.0         0.0         0.0         0.0                                                                                                                                                                                        
                                                                                                                                                                                                                                             
julia> g2
13×5 Array{Float64,2}:                                                                                                                                                                                                                       
 0.0  0.0  0.0  0.0  0.0                                                                                                                                                                                                                     
 0.0  0.0  0.0  0.0  0.0                                                                                                                                                                                                                     
 0.0  0.0  0.0  0.0  0.0                                                                                                                                                                                                                     
 0.0  0.0  0.0  0.0  0.0                                                                                                                                                                                                                     
 0.0  0.0  0.0  0.0  0.0                                                                                                                                                                                                                     
 0.0  0.0  0.0  0.0  0.0                                                                                                                                                                                                                     
 0.0  0.0  0.0  0.0  0.0                                                                                                                                                                                                                     
 0.0  0.0  0.0  0.0  0.0                                                                                                                                                                                                                     
 0.0  0.0  0.0  0.0  0.0                                                                                                                                                                                                                     
 0.0  0.0  0.0  0.0  0.0                                                                                                                                                                                                                     
 0.0  0.0  0.0  0.0  0.0                                                                                                                                                                                                                     
 0.0  0.0  0.0  0.0  0.0                                                                                                                                                                                                                     
 0.0  0.0  0.0  0.0  0.0                                                                                                                                                                                                                     
```
Images went with the advice of the community and adopted the first dimension as "y" when images are displayed.

**Comment by mauro3** [comment]
I just translated the source code into a doc-string: https://github.com/JuliaImages/Images.jl/pull/672/files#diff-aca1e75c3d7918f0b57dc20de4a7120fR108.  If that is wrong, then there is a bug.

**Comment by timholy** [comment]
It's more that the variable names are outdated. Really those could be called `dim1` and `dim2`, it's just that now `dim1` corresponds to "vertical" (it didn't used to).

**Comment by mauro3** [comment]
Like so?  I feel as grad_x and grad_y feature elsewhere, renaming grad_x-> dim would be a bit larger than what I hoped for with this PR.

**Comment by timholy** [comment]
Thanks!

**Pull request merged**
