### PR TITLE
deprecate hausdorff_distance in favour of ImageDistances

### PR DESCRIPTION
**Pull request by Evizero**
Deprecation strategy for #694. Note that I am not comfortable with merging something like this by myself, so I will leave this open until Prof. Holy got a chance to weigh in

cc: @juliohm

### CODE REVIEW

**Comment by Evizero** [comment]
Should we go ahead with this?

**Comment by timholy** [comment]
https://github.com/JuliaImages/Images.jl/pull/694#issuecomment-354139842 seemed to suggest that just `@reexport`ing ImageDistances might be the better choice? We could still do this if someone adds dozens of metrics to ImageDistances...

**Comment by juliohm** [comment]
Thank you for the follow up @Evizero , please feel free to go ahead and merge. :+1:

**Comment by juliohm** [comment]
Can this be merged?

**Comment by Evizero** [comment]
I'll do the reexport strategy and open a new PR

**Pull request closed without merging**
